
DROP TABLE IF EXISTS assessments;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS client_address;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS employee_project;
DROP TABLE IF EXISTS findings;
DROP TABLE IF EXISTS hostvulns;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS project_employee;
DROP TABLE IF EXISTS project_location;
DROP TABLE IF EXISTS project_status;
DROP TABLE IF EXISTS scans;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS vulnerabilities;
DROP TABLE IF EXISTS webvulns;
